In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
print(a.ndim)
print(b.ndim)

1
2


In [5]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
print(a.dtype)
print(b.dtype)

int32
float64


In [7]:
# размер в байтах 1 элемента
print(a.itemsize)
print(b.itemsize)

4
8


In [8]:
print(a.nbytes)
print(b.nbytes)

12
48


In [9]:
print(a.size)
print(b.size)

3
6


## Accessing/Changing specific elements, rows, columns

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specific element [r, c]
print(a[1, 5])
# Get a specific row 
print(a[0, :])
# Get a specific column
print(a[:, 2])
# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:-1:2])

13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]


In [16]:
# Update a specific element
a[1,5] = 20
print(a)
# Update a specific column
a[:,2] = [1,2]
print(a)

# Update a specific row
a[1,:] = a[0,:]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[1 2 1 4 5 6 7]
 [1 2 1 4 5 6 7]]


In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [27]:
A = np.delete(b, 1, 0)  # delete second row of A
print(A)
C = np.delete(b, 1, 1)  # delete second column of C
print(C)
#start,end,step
C1 = np.delete(b, np.s_[1:2:], 1)  # delete second column of C
print(C1)
D = np.delete(b, 1, 2)  # delete second inner-column of D
print(D)

[[[1 2]
  [9 9]]]
[[[1 2]]

 [[5 6]]]
[[[1 2]]

 [[5 6]]]
[[[1]
  [9]]

 [[5]
  [8]]]


## Initializing Different Types of Arrays

In [29]:
print(np.zeros((2,3)))
print(np.ones((4,2,2), dtype='int32'))
print(np.full((2,2), 99))
print(np.full_like(a, 4))
print(np.random.rand(4,2))
print(np.random.randint(-4,8, size=(3,3)))
print(np.identity(5))

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[99 99]
 [99 99]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[0.8772317  0.06539215]
 [0.11586938 0.8801324 ]
 [0.87440072 0.00352852]
 [0.56136    0.6821364 ]]
[[ 6  3  3]
 [-1 -2  0]
 [-3  0  4]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


## Mathematics

In [37]:
a = np.array([1,2,3,4])
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a / 2)

b = np.array([1,0,1,0])
print(a + b)
print(a ** 2)
print(np.cos(a))

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[2 2 4 4]
[ 1  4  9 16]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [38]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [39]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [42]:
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.max(stats, axis=1))
print(np.sum(stats, axis=0))
print(np.sum(stats, axis=1))
print(np.sum(stats))

1
[3 6]
[5 7 9]
[ 6 15]
21


## Reorganizing Arrays

In [45]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [58]:

stack = np.vstack([v1,v2,v1,v2])
print(stack)
cond = (~((stack > 3) & (stack < 7)))
print(cond)
print(stack[cond])
print(np.argwhere((~((stack > 3) & (stack < 7)))))
print(stack[stack>5])
stack[stack>5] = 100
print(stack[stack>5])

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[ True  True  True False]
 [False False  True  True]
 [ True  True  True False]
 [False False  True  True]]
[1 2 3 7 8 1 2 3 7 8]
[[0 0]
 [0 1]
 [0 2]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [3 2]
 [3 3]]
[6 7 8 6 7 8]
[100 100 100 100 100 100]
